'use strict';
angular.module('app.controllers', []).controller('AppCtrl', [
  '$scope', '$location', '$modal', function($scope, $location, $modal) {
    $scope.isSpecificPage = function() {
      var path;
      path = $location.path();
      return _.contains(['/404', '/print'], path);
    };
    $scope.getContentClass = function() {
      var className;
      className = "animate-fade-up";
      if ($scope.isSpecificPage()) {
        className += " page-top";
      }
      if ($scope.linksOpen) {
        className += " links-open";
      }
      return className;
    };
    $scope.getWholePageClass = function() {
      if ($scope.linksOpen) {
        return "whole-page links-open";
      }
      return "whole-page";
    };
    $scope.getLinksPaneClass = function() {
      if ($scope.linksOpen) {
        return "links-pane links-open";
      }
      return "links-pane";
    };
    $scope.isTabbedPage = function() {
      var path;
      path = $location.path();
      return _.contains(['/map', '/list'], path);
    };
    $scope.linksOpen = false;
    $scope.onToggleLinks = function() {
      $scope.linksOpen = !$scope.linksOpen;
    };
    return $scope.onShowHelp = function() {
      var modalInstance;
      modalInstance = $modal.open({
        templateUrl: "views/helpModal.html",
        controller: 'HelpModalCtrl',
        resolve: {}
      });
    };
  }
]).controller('NavCtrl', [
  '$scope', 'taskStorage', 'filterFilter', function($scope, taskStorage, filterFilter) {
    var tasks;
    tasks = $scope.tasks = taskStorage.get();
    $scope.taskRemainingCount = filterFilter(tasks, {
      completed: false
    }).length;
    return $scope.$on('taskRemaining:changed', function(event, count) {
      return $scope.taskRemainingCount = count;
    });
  }
]).controller('DashboardCtrl', ['$scope', function($scope) {}]).controller('HelpModalCtrl', [
  '$scope', '$modalInstance', function($scope, $modalInstance) {
    $scope.ok = function() {
      $modalInstance.dismiss("cancel");
    };
  }
]);

// ---
// generated by coffee-script 1.9.2